### ISSUE TITLE
proejct description needs update

### ISSUE THREAD

**Issue by vzaliva** [rems-project/coq-cheri-capabilities#1]
https://github.com/rems-project/coq-cheri-capabilities/blob/7ac5e76da708960c2aad7f6ca4cba2e823fdbbe6/dune-project#L15-L18

**Comment by vzaliva** [comment]
Also here https://github.com/rems-project/coq-cheri-capabilities/blob/7ac5e76da708960c2aad7f6ca4cba2e823fdbbe6/coq-cheri-capabilities.opam#LL3C1-L3C35

**Comment by ric-almeida** [comment]
I have updated this now. @vzaliva let me know if you think it needs improvement.

**Comment by vzaliva** [comment]
the dune-project file seems unchanged. See "synopsis" and "description" fields.
